/*
API version: v2.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// Compile-time check to ensure the struct implements the interface
var _ MappedNullable = &UtilsScanProgressStatusRequest{}

// UtilsScanProgressStatusRequest struct for sending progress updates to backend
type UtilsScanProgressStatusRequest struct {
	ScanType       string  `json:"scan_type"`
	ScanId         string  `json:"scan_id"`
	ProgressStatus *string `json:"progress_status,omitempty"`
}

// NewUtilsScanProgressStatusRequest instantiates a new UtilsScanProgressStatusRequest object
func NewUtilsScanProgressStatusRequest(scanType string, scanId string, progressStatus *string) *UtilsScanProgressStatusRequest {
	return &UtilsScanProgressStatusRequest{
		ScanType:       scanType,
		ScanId:         scanId,
		ProgressStatus: progressStatus,
	}
}

// GetScanType returns the ScanId field value
func (o *UtilsScanProgressStatusRequest) GetScanType() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.ScanType
}

// SetScanType sets field value
func (o *UtilsScanProgressStatusRequest) SetScanType(v string) {
	o.ScanType = v
}

// GetScanId returns the ScanId field value
func (o *UtilsScanProgressStatusRequest) GetScanId() string {
	if o == nil {
		var ret string
		return ret
	}
	return o.ScanId
}

// SetScanId sets field value
func (o *UtilsScanProgressStatusRequest) SetScanId(v string) {
	o.ScanId = v
}

// GetProgressStatus returns the ProgressStatus field value if set, zero value otherwise
func (o *UtilsScanProgressStatusRequest) GetProgressStatus() string {
	if o == nil || o.ProgressStatus == nil {
		var ret string
		return ret
	}
	return *o.ProgressStatus
}

// SetProgressStatus sets field value
func (o *UtilsScanProgressStatusRequest) SetProgressStatus(v string) {
	o.ProgressStatus = &v
}

// HasProgressStatus returns a boolean if a field has been set
func (o *UtilsScanProgressStatusRequest) HasProgressStatus() bool {
	return o != nil && o.ProgressStatus != nil
}

// ToMap implements MappedNullable interface
func (o UtilsScanProgressStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scan_type"] = o.ScanType
	toSerialize["scan_id"] = o.ScanId
	if o.ProgressStatus != nil {
		toSerialize["progress_status"] = o.ProgressStatus
	}
	return toSerialize, nil
}

// MarshalJSON custom marshaller for JSON
func (o UtilsScanProgressStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return nil, err
	}
	return json.Marshal(toSerialize)
}

// MarshalJSONWithoutReadOnly omits read-only fields (if any)
func (o UtilsScanProgressStatusRequest) MarshalJSONWithoutReadOnly() ([]byte, error) {
	return o.MarshalJSON()
}
